@hostname = localhost
@port = 6001
@host = {{hostname}}:{{port}}
@contentType = application/json

@workflowID = BANK_TRANSFER-1710144624

### Verify OTP

POST http://{{host}}/verifications/otp
Content-Type: {{contentType}}

{
  "workflow_id": "{{workflowID}}",
  "token": "token",
  "code": "code",
  "trace": "trace"
}